version: '3.9'
services:        
  no-kill-inventory:
    image: no-kill-inventory
    build:
      context: .
      dockerfile: No-Kill-Inventory/Dockerfile
    pull_policy: always
    restart: always
    ports: 
      - 80:8080